CREATE TABLE IF NOT EXISTS `your_data_set.natality`(
  id INT64,
  source_year INT64,
  year INT64,
  month INT64,
  day INT64,
  wday INT64,
  state STRING,
  is_male bool,
  child_race INT64,
  weight_pounds FLOAT64,
  plurality INT64,
  apgar_1min INT64,
  mother_residence_state STRING,
  mother_race int64,
  mother_age int64,
  gestation_weeks INT64,
  lmp STRING,
  mother_married bool,
  mother_birth_state STRING,
  cigarette_use bool,
  cigarettes_per_day INT64,
  alcohol_use bool,
  drinks_per_week INT64,
  weight_gain_pounds INT64,
  born_alive_alive INT64,
  born_alive_dead INT64,
  born_dead INT64,
  ever_born INT64,
  father_race INT64,
  father_age INT64,
  record_weight INT64
)
PARTITION BY source_year AS
SELECT * FROM bigquery-public-data.samples.natality;